server:
  port: 8080

spring:
  application:
    name: sia-app-web
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/dbhistorialactivos
    username: usuario_soporte
    password: 2024
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true