server:
  port: 8080 # Puerto estándar de Spring Boot

spring:
  application:
    name: sia-app-web # Nombre de la aplicación
  datasource:
    driver-class-name: org.postgresql.Driver # Controlador de la base de datos
    url: jdbc:postgresql://dbhistorialactivos.c1m4ueo42jbz.us-east-2.rds.amazonaws.com:5432/dbhistorialactivosmuni # URL de la base de datos
    username: usuario_sia # Nombre de usuario de la base de datos
    password: muni_2024_sia # Contraseña de la base de datos
  jpa:
    hibernate:
      ddl-auto: none # Actualizar la base de datos
    database: postgresql # Tipo de base de datos
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Plataforma de la base de datos
    show-sql: false # Mostrar SQL
logging:
  level:
    org:
      springframework: INFO
chatbot:
  api:
    key: 2bb5e892c509dc5e3a09c88885770569437391acff5da87aafbf01259960076e # deprecada
